/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package shop;

import java.awt.Color;
import java.sql.Connection;
import java.util.Locale;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;

import ShopDao.conexionDB;
import ShopDao.int_detalles_venta;
import ShopDao.int_detalles_ventaDao;
import ShopDao.int_detalles_ventaImp;

import ShopDao.int_producto;
import ShopDao.int_productoDao;
import ShopDao.int_productoImp;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.intellijthemes.FlatGruvboxDarkHardIJTheme;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialLighterIJTheme;
import edit_product.edit_product;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author USUARIO
 */
public class app_shop extends javax.swing.JFrame {

    /**
     * Creates new form app_shop
     */
    //static Connection conn = null;
    //static String url = "jdbc:mariadb://localhost/shop_db";
    //static String user = "intuser";
    //static String password = "DCBA";
    int xMouse, yMouse;
    boolean visible=true;
    //DefaultTableModel modeloTabla = new DefaultTableModel();
    CustomTableModel modeloTabla = new CustomTableModel(new Object[]{"Nombre", "Precio", "Stock", "Descripción", "Imagen"}, 0);
    public app_shop() {
        initComponents();
        Locale.setDefault(new Locale("es", "ES"));
        this.setLocationRelativeTo(null); //Centrar la pantalla
        
               
        
        // Oculta el boton de editar 
        btneditar.setVisible(visible);
        editar_btn.setVisible(visible);
        
        //conexionDB conexion1 = new conexionDB(url, user, password);
        //Connection conn = conexion1.establecerConexion();
        
        //String[] titulo=new String[]{"Nombre","Precio","Stock","Descripción","imagen"};
        //modeloTabla.setColumnIdentifiers(titulo);
        Tabla1.setModel(modeloTabla);
        //modeloTabla.addRow(new Object[]{"asus","100","2","laptop"});
        showProducts(1); 
        titulo_categoria.setText(btn_categ_1.getText());
    }
    login UID = new login();
    Connection conn = UID.getConn();
    int_productoImp intProductoDao=new int_productoImp(conn); 
    int_producto intProducto;
    
    ArrayList dataList;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void showProducts(int categoria) {
        //titulo_categoria.setText(btn_categ_4.getText());
        modeloTabla.setRowCount(0);

        Object[] datoLista = new Object[5]; // Asumiendo que hay una columna adicional para la imagen
        dataList = intProductoDao.getDataWithImag(categoria);

        for (int i = 0; i < dataList.size(); i++) {
            intProducto = (int_producto) dataList.get(i);
            datoLista[0] = intProducto.getNombre();
            datoLista[1] = intProducto.getPrecio();
            datoLista[2] = intProducto.getStock();
            datoLista[3] = intProducto.getDescripción();

            // Nuevo método para mostrar la imagen en la columna "imagen"
            showImgColumn(datoLista, 4, intProducto.getImagen());

            modeloTabla.addRow(datoLista);
        }
    }
    
    // Nuevo método para mostrar la imagen en la columna "imagen"
    private void showImgColumn(Object[] datoLista, int columnaImagen, byte[] imagenBytes) {
        try {
            // Crear ImageIcon desde bytes
            ImageIcon imagenIcon = new ImageIcon(imagenBytes);

            // Obtener las dimensiones originales de la imagen
            int anchoOriginal = imagenIcon.getIconWidth();
            int altoOriginal = imagenIcon.getIconHeight();

            // Calcular el nuevo tamaño para mantener el aspecto ratio de la imagen
            int nuevoAncho = 50; // ajusta según tus preferencias
            int nuevoAlto = (int) ((double) nuevoAncho / anchoOriginal * altoOriginal);

            // Escalar la imagen manteniendo el aspecto
            Image imagenOriginal = imagenIcon.getImage();
            Image imagenEscalada = imagenOriginal.getScaledInstance(nuevoAncho, nuevoAlto, Image.SCALE_SMOOTH);

            // Crear un nuevo ImageIcon con la imagen escalada y fondo transparente
            ImageIcon imagenEscaladaIcon = new ImageIcon(imagenEscalada);

            // Establecer la imagen escalada en el array de datos
            datoLista[columnaImagen] = imagenEscaladaIcon;
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public class CustomTableModel extends DefaultTableModel {

        public CustomTableModel(Object[] columnNames, int rowCount) {
            super(columnNames, rowCount);
        }

        @Override
        public Class<?> getColumnClass(int columnIndex) {
            return columnIndex == 4 ? ImageIcon.class : Object.class; // 4 es el índice de la columna "imagen"
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        fdbg = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        categoria = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        categ_1 = new javax.swing.JPanel();
        btn_categ_1 = new javax.swing.JLabel();
        categ_2 = new javax.swing.JPanel();
        btn_categ_2 = new javax.swing.JLabel();
        categ_3 = new javax.swing.JPanel();
        btn_categ_3 = new javax.swing.JLabel();
        categ_4 = new javax.swing.JPanel();
        btn_categ_4 = new javax.swing.JLabel();
        btneditar = new javax.swing.JPanel();
        editar_btn = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        barra_superior = new javax.swing.JPanel();
        btnmin = new javax.swing.JPanel();
        lbl_min = new javax.swing.JLabel();
        exitbtn = new javax.swing.JPanel();
        lbl_salir = new javax.swing.JLabel();
        titulo_categoria = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        txt_busqueda = new javax.swing.JTextField();
        btnbuscar = new javax.swing.JPanel();
        buscar_btn = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fdbg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fdbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        fdbg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bg.add(fdbg, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, 310, 148));

        nombre.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        nombre.setForeground(new java.awt.Color(255, 204, 51));
        nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombre.setText("SHOP ONLINE PLUS");
        nombre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bg.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 150, 310, -1));

        categoria.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        categoria.setForeground(new java.awt.Color(255, 204, 51));
        categoria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        categoria.setText("CATEGORIAS");
        bg.add(categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 210, 300, -1));

        jSeparator1.setForeground(new java.awt.Color(255, 204, 51));
        bg.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 250, 300, 16));

        jSeparator2.setForeground(new java.awt.Color(255, 204, 51));
        bg.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 190, 300, 16));

        categ_1.setBackground(new java.awt.Color(13, 25, 75));

        btn_categ_1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btn_categ_1.setForeground(new java.awt.Color(255, 204, 51));
        btn_categ_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_categ_1.setText("Computadoras y Portátiles");
        btn_categ_1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_categ_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_categ_1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_categ_1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_categ_1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout categ_1Layout = new javax.swing.GroupLayout(categ_1);
        categ_1.setLayout(categ_1Layout);
        categ_1Layout.setHorizontalGroup(
            categ_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
            .addGroup(categ_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(categ_1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btn_categ_1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        categ_1Layout.setVerticalGroup(
            categ_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(categ_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(categ_1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btn_categ_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        bg.add(categ_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 290, 320, 40));

        categ_2.setBackground(new java.awt.Color(13, 25, 75));

        btn_categ_2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btn_categ_2.setForeground(new java.awt.Color(255, 204, 51));
        btn_categ_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_categ_2.setText("Electrónica de Consumo");
        btn_categ_2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_categ_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_categ_2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_categ_2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_categ_2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout categ_2Layout = new javax.swing.GroupLayout(categ_2);
        categ_2.setLayout(categ_2Layout);
        categ_2Layout.setHorizontalGroup(
            categ_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_categ_2, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
        );
        categ_2Layout.setVerticalGroup(
            categ_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_categ_2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        bg.add(categ_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 340, 320, 40));

        categ_3.setBackground(new java.awt.Color(13, 25, 75));

        btn_categ_3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btn_categ_3.setForeground(new java.awt.Color(255, 204, 51));
        btn_categ_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_categ_3.setText("Gaming");
        btn_categ_3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_categ_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_categ_3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_categ_3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_categ_3MouseExited(evt);
            }
        });

        javax.swing.GroupLayout categ_3Layout = new javax.swing.GroupLayout(categ_3);
        categ_3.setLayout(categ_3Layout);
        categ_3Layout.setHorizontalGroup(
            categ_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
            .addGroup(categ_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(categ_3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btn_categ_3, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        categ_3Layout.setVerticalGroup(
            categ_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(categ_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(categ_3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btn_categ_3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        bg.add(categ_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 390, 320, 40));

        categ_4.setBackground(new java.awt.Color(13, 25, 75));

        btn_categ_4.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btn_categ_4.setForeground(new java.awt.Color(255, 204, 51));
        btn_categ_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_categ_4.setText("Electrodomésticos ");
        btn_categ_4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_categ_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_categ_4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_categ_4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_categ_4MouseExited(evt);
            }
        });

        javax.swing.GroupLayout categ_4Layout = new javax.swing.GroupLayout(categ_4);
        categ_4.setLayout(categ_4Layout);
        categ_4Layout.setHorizontalGroup(
            categ_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
            .addGroup(categ_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(categ_4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btn_categ_4, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        categ_4Layout.setVerticalGroup(
            categ_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(categ_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(categ_4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(btn_categ_4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        bg.add(categ_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 440, 320, 40));

        btneditar.setBackground(new java.awt.Color(13, 25, 75));

        editar_btn.setForeground(new java.awt.Color(255, 204, 51));
        editar_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editar_btn.setText("Editar");
        editar_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editar_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editar_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editar_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editar_btnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btneditarLayout = new javax.swing.GroupLayout(btneditar);
        btneditar.setLayout(btneditarLayout);
        btneditarLayout.setHorizontalGroup(
            btneditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editar_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
        );
        btneditarLayout.setVerticalGroup(
            btneditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editar_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bg.add(btneditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 530, 320, 40));

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/2.jpg"))); // NOI18N
        logo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bg.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, 320, 600));

        barra_superior.setBackground(new java.awt.Color(255, 255, 255));
        barra_superior.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barra_superiorMouseDragged(evt);
            }
        });
        barra_superior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barra_superiorMousePressed(evt);
            }
        });

        btnmin.setBackground(new java.awt.Color(255, 255, 255));

        lbl_min.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lbl_min.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_min.setText("-");
        lbl_min.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_minMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_minMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_minMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnminLayout = new javax.swing.GroupLayout(btnmin);
        btnmin.setLayout(btnminLayout);
        btnminLayout.setHorizontalGroup(
            btnminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_min, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        btnminLayout.setVerticalGroup(
            btnminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_min, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        exitbtn.setBackground(new java.awt.Color(255, 255, 255));

        lbl_salir.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lbl_salir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_salir.setText("X");
        lbl_salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_salirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_salirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_salirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitbtnLayout = new javax.swing.GroupLayout(exitbtn);
        exitbtn.setLayout(exitbtnLayout);
        exitbtnLayout.setHorizontalGroup(
            exitbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitbtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        exitbtnLayout.setVerticalGroup(
            exitbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout barra_superiorLayout = new javax.swing.GroupLayout(barra_superior);
        barra_superior.setLayout(barra_superiorLayout);
        barra_superiorLayout.setHorizontalGroup(
            barra_superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barra_superiorLayout.createSequentialGroup()
                .addComponent(btnmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(exitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 928, Short.MAX_VALUE))
        );
        barra_superiorLayout.setVerticalGroup(
            barra_superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(exitbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bg.add(barra_superior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 30));

        titulo_categoria.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        titulo_categoria.setText("Ejemplo de titulo");
        bg.add(titulo_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 95, 370, 30));

        titulo.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        titulo.setText("CATEGORIA");
        bg.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 150, 30));

        txt_busqueda.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txt_busqueda.setForeground(new java.awt.Color(153, 153, 153));
        txt_busqueda.setText("Ingrese una busqueda");
        txt_busqueda.setBorder(null);
        txt_busqueda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_busquedaMousePressed(evt);
            }
        });
        bg.add(txt_busqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 230, 30));

        btnbuscar.setBackground(new java.awt.Color(13, 25, 75));

        buscar_btn.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        buscar_btn.setForeground(new java.awt.Color(255, 255, 255));
        buscar_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buscar_btn.setText("Buscar");
        buscar_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buscar_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscar_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buscar_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buscar_btnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnbuscarLayout = new javax.swing.GroupLayout(btnbuscar);
        btnbuscar.setLayout(btnbuscarLayout);
        btnbuscarLayout.setHorizontalGroup(
            btnbuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buscar_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
        btnbuscarLayout.setVerticalGroup(
            btnbuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buscar_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bg.add(btnbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 50, 70, 30));

        jSeparator3.setForeground(new java.awt.Color(102, 102, 102));
        bg.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 710, 20));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 230, -1));

        jScrollPane2.setViewportView(Tabla1);

        bg.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 700, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_minMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_minMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_lbl_minMouseClicked

    private void lbl_minMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_minMouseEntered
        btnmin.setBackground(Color.red);
        lbl_min.setForeground(Color.white);
    }//GEN-LAST:event_lbl_minMouseEntered

    private void lbl_minMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_minMouseExited
        btnmin.setBackground(Color.white);
        lbl_min.setForeground(Color.black);
    }//GEN-LAST:event_lbl_minMouseExited

    private void lbl_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_salirMouseClicked
        Object[] opciones = {"Sí", "No"};

        int respuesta = JOptionPane.showOptionDialog(
            this,
            "¿Estás seguro de cerrar la aplicación?",
            "Confirmar cierre",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE,
            null,
            opciones,
            opciones[0]); // Puedes cambiar este índice para establecer el botón predeterminado

        if (respuesta == JOptionPane.YES_OPTION) {
            // Si el usuario elige "Sí", cierra la aplicación
            System.exit(0);
        } else {
            // Si el usuario elige "No" o cierra el cuadro de diálogo, no hace nada
        }
    }//GEN-LAST:event_lbl_salirMouseClicked

    private void lbl_salirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_salirMouseEntered
        exitbtn.setBackground(Color.red);
        lbl_salir.setForeground(Color.white);
    }//GEN-LAST:event_lbl_salirMouseEntered

    private void lbl_salirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_salirMouseExited
        exitbtn.setBackground(Color.white);
        lbl_salir.setForeground(Color.black);
    }//GEN-LAST:event_lbl_salirMouseExited

    private void barra_superiorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barra_superiorMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_barra_superiorMouseDragged

    private void barra_superiorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barra_superiorMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_barra_superiorMousePressed

    private void btn_categ_1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_categ_1MouseEntered
         categ_1.setBackground(new Color(69,81,107));
    }//GEN-LAST:event_btn_categ_1MouseEntered

    private void btn_categ_1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_categ_1MouseExited
        categ_1.setBackground(new Color(13,25,75));
    }//GEN-LAST:event_btn_categ_1MouseExited

    private void btn_categ_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_categ_1MouseClicked
       // lo que hace esta categoria uno 
       titulo_categoria.setText(btn_categ_1.getText());
       showProducts(1);
       /*titulo_categoria.setText(btn_categ_1.getText());
       modeloTabla.setRowCount(0);
      
       Object[] datoLista=new Object[5];
       dataList=intProductoDao.getDataWithImag(1);
       for(int i=0;i<dataList.size();i++){
       intProducto= (int_producto) dataList.get(i);
       datoLista[0]=intProducto.getNombre();
       datoLista[1]=intProducto.getPrecio();
       datoLista[2]=intProducto.getStock();
       datoLista[3]=intProducto.getDescripción();
       try{
           
           byte [] imagen = intProducto.getImagen();
           BufferedImage buffer= null;
           InputStream inputStream = new ByteArrayInputStream(imagen);
           buffer= ImageIO.read(inputStream);
           ImageIcon icon= new ImageIcon(buffer.getScaledInstance(30, 30, 0));
           datoLista[4]=new JLabel(icon);
       }catch(Exception e){
           datoLista[4]=new JLabel("no imagen");
       }
       modeloTabla.addRow(datoLista);
       
       }
       Tabla1.setModel(modeloTabla);*/
       
       
    }//GEN-LAST:event_btn_categ_1MouseClicked

    private void btn_categ_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_categ_2MouseClicked
         // lo que hace esta categoria dos
         titulo_categoria.setText(btn_categ_2.getText());
         showProducts(2);
         /*titulo_categoria.setText(btn_categ_2.getText());
       modeloTabla.setRowCount(0);
      
       Object[] datoLista=new Object[5];
       dataList=intProductoDao.getDataWithImag(2);
       for(int i=0;i<dataList.size();i++){
       intProducto= (int_producto) dataList.get(i);
       datoLista[0]=intProducto.getNombre();
       datoLista[1]=intProducto.getPrecio();
       datoLista[2]=intProducto.getStock();
       datoLista[3]=intProducto.getDescripción();
       try{
           
           byte [] imagen = intProducto.getImagen();
           BufferedImage buffer= null;
           InputStream inputStream = new ByteArrayInputStream(imagen);
           buffer= ImageIO.read(inputStream);
           ImageIcon icon= new ImageIcon(buffer.getScaledInstance(30, 30, 0));
           datoLista[4]=new JLabel(icon);
       }catch(Exception e){
           datoLista[4]=new JLabel("no imagen");
       }
       modeloTabla.addRow(datoLista);
       }*/
    }//GEN-LAST:event_btn_categ_2MouseClicked

    private void btn_categ_2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_categ_2MouseEntered
        categ_2.setBackground(new Color(69,81,107));
    }//GEN-LAST:event_btn_categ_2MouseEntered

    private void btn_categ_2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_categ_2MouseExited
         categ_2.setBackground(new Color(13,25,75));
    }//GEN-LAST:event_btn_categ_2MouseExited

    private void btn_categ_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_categ_3MouseClicked
         // lo que hace esta categoria tres 
         titulo_categoria.setText(btn_categ_3.getText());
         showProducts(3);
         /*titulo_categoria.setText(btn_categ_3.getText());
       modeloTabla.setRowCount(0);
      
       Object[] datoLista=new Object[5];
       dataList=intProductoDao.getDataWithImag(3);
       for(int i=0;i<dataList.size();i++){
       intProducto= (int_producto) dataList.get(i);
       datoLista[0]=intProducto.getNombre();
       datoLista[1]=intProducto.getPrecio();
       datoLista[2]=intProducto.getStock();
       datoLista[3]=intProducto.getDescripción();
       try{
           
           byte [] imagen = intProducto.getImagen();
           BufferedImage buffer= null;
           InputStream inputStream = new ByteArrayInputStream(imagen);
           buffer= ImageIO.read(inputStream);
           ImageIcon icon= new ImageIcon(buffer.getScaledInstance(30, 30, 0));
           datoLista[4]=new JLabel(icon);
       }catch(Exception e){
           datoLista[4]=new JLabel("no imagen");
       }
       modeloTabla.addRow(datoLista);
       }*/
    }//GEN-LAST:event_btn_categ_3MouseClicked

    private void btn_categ_3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_categ_3MouseEntered
         categ_3.setBackground(new Color(69,81,107));
    }//GEN-LAST:event_btn_categ_3MouseEntered

    private void btn_categ_3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_categ_3MouseExited
         categ_3.setBackground(new Color(13,25,75));
    }//GEN-LAST:event_btn_categ_3MouseExited

    private void btn_categ_4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_categ_4MouseClicked
        // lo que hace esta categoria cuatro 
        titulo_categoria.setText(btn_categ_4.getText());
        showProducts(4);
        /*titulo_categoria.setText(btn_categ_4.getText());
       modeloTabla.setRowCount(0);
      
       Object[] datoLista=new Object[5];
       dataList=intProductoDao.getDataWithImag(4);
       for(int i=0;i<dataList.size();i++){
       intProducto= (int_producto) dataList.get(i);
       datoLista[0]=intProducto.getNombre();
       datoLista[1]=intProducto.getPrecio();
       datoLista[2]=intProducto.getStock();
       datoLista[3]=intProducto.getDescripción();
       try{
           
           byte [] imagen = intProducto.getImagen();
           BufferedImage buffer= null;
           InputStream inputStream = new ByteArrayInputStream(imagen);
           buffer= ImageIO.read(inputStream);
           ImageIcon icon= new ImageIcon(buffer.getScaledInstance(30, 30, 0));
           datoLista[4]=new JLabel(icon);
       }catch(Exception e){
           datoLista[4]=new JLabel("no imagen");
       }
       modeloTabla.addRow(datoLista);
       }*/
    }//GEN-LAST:event_btn_categ_4MouseClicked

    private void btn_categ_4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_categ_4MouseEntered
        categ_4.setBackground(new Color(69,81,107));
    }//GEN-LAST:event_btn_categ_4MouseEntered

    private void btn_categ_4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_categ_4MouseExited
        categ_4.setBackground(new Color(13,25,75));
    }//GEN-LAST:event_btn_categ_4MouseExited

    private void txt_busquedaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_busquedaMousePressed
        if (txt_busqueda.getText().equals("Ingrese una busqueda")){
            txt_busqueda.setText("");
            txt_busqueda.setForeground(Color.black);
        }
    }//GEN-LAST:event_txt_busquedaMousePressed

    private void buscar_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscar_btnMouseClicked
        // lo que hace la barra de busqueda 
    }//GEN-LAST:event_buscar_btnMouseClicked

    private void buscar_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscar_btnMouseEntered
      btnbuscar.setBackground(new Color(69,81,107));
    }//GEN-LAST:event_buscar_btnMouseEntered

    private void buscar_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscar_btnMouseExited
       btnbuscar.setBackground(new Color(13,25,75));
    }//GEN-LAST:event_buscar_btnMouseExited

    private void editar_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editar_btnMouseExited
        // TODO add your handling code here:
        btneditar.setBackground(new Color(13,25,75));
    }//GEN-LAST:event_editar_btnMouseExited

    private void editar_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editar_btnMouseEntered
        // TODO add your handling code here:
        btneditar.setBackground(new Color(69,81,107));
    }//GEN-LAST:event_editar_btnMouseEntered

    private void editar_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editar_btnMouseClicked
                edit_product edit = new edit_product();
                edit.setVisible(true);
                dispose();
                
                
                dispose();    }//GEN-LAST:event_editar_btnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
            //FlatGruvboxDarkHardIJTheme.setup();
             FlatMaterialLighterIJTheme.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new app_shop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla1;
    private javax.swing.JPanel barra_superior;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel btn_categ_1;
    private javax.swing.JLabel btn_categ_2;
    private javax.swing.JLabel btn_categ_3;
    private javax.swing.JLabel btn_categ_4;
    private javax.swing.JPanel btnbuscar;
    private javax.swing.JPanel btneditar;
    private javax.swing.JPanel btnmin;
    private javax.swing.JLabel buscar_btn;
    private javax.swing.JPanel categ_1;
    private javax.swing.JPanel categ_2;
    private javax.swing.JPanel categ_3;
    private javax.swing.JPanel categ_4;
    private javax.swing.JLabel categoria;
    private javax.swing.JLabel editar_btn;
    private javax.swing.JPanel exitbtn;
    private javax.swing.JLabel fdbg;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lbl_min;
    private javax.swing.JLabel lbl_salir;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel titulo_categoria;
    private javax.swing.JTextField txt_busqueda;
    // End of variables declaration//GEN-END:variables
}
