/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package shop;
import ShopDao.conexionDB;
import ShopDao.int_tipo_usuariosIMP;
import ShopDao.int_usuario;
import ShopDao.int_usuarioDaoImp;
import java.awt.Color;
import java.sql.Connection;
import java.util.Locale;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

import static shop.login.user_id;
/**
 *
 * @author ajota
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    int xMouse, yMouse;
    private boolean aceptoTerminos = false;
    private boolean aceptoTerminos_2 = false;
    private boolean camposllenos = false;
    private boolean usuarionuevo = false;
    public Registro() {
        initComponents();
        Locale.setDefault(new Locale("es", "ES"));
        this.setLocationRelativeTo(null); //Centrar la pantalla
    }
     public static Connection conn;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fdbg = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        barra_superior = new javax.swing.JPanel();
        btnmin = new javax.swing.JPanel();
        lbl_min = new javax.swing.JLabel();
        exitbtn = new javax.swing.JPanel();
        lbl_salir = new javax.swing.JLabel();
        txt_user = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        user_nombre = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        txt_apellido = new javax.swing.JTextField();
        user_apellido = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        correo = new javax.swing.JLabel();
        txt_correo = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        user_nombre1 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        txt_pass = new javax.swing.JPasswordField();
        direccion = new javax.swing.JLabel();
        txt_direccion = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        boton_registro = new javax.swing.JPanel();
        btn_registro = new javax.swing.JLabel();
        lbl_atras = new javax.swing.JLabel();
        aceptoterminos = new javax.swing.JCheckBox();
        cambiar_pass = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fdbg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fdbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        fdbg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(fdbg, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, 280, 160));

        nombre.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        nombre.setForeground(new java.awt.Color(255, 204, 51));
        nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombre.setText("SHOP ONLINE PLUS");
        nombre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, 280, 30));

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1.jpg"))); // NOI18N
        logo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 280, 500));

        titulo.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("REGISTRO NUEVO USUARIO");
        jPanel1.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        user.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        user.setText("USUARIO");
        jPanel1.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        barra_superior.setBackground(new java.awt.Color(255, 255, 255));
        barra_superior.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barra_superiorMouseDragged(evt);
            }
        });
        barra_superior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barra_superiorMousePressed(evt);
            }
        });

        btnmin.setBackground(new java.awt.Color(255, 255, 255));

        lbl_min.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lbl_min.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_min.setText("-");
        lbl_min.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_minMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_minMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_minMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnminLayout = new javax.swing.GroupLayout(btnmin);
        btnmin.setLayout(btnminLayout);
        btnminLayout.setHorizontalGroup(
            btnminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_min, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        btnminLayout.setVerticalGroup(
            btnminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_min, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        exitbtn.setBackground(new java.awt.Color(255, 255, 255));

        lbl_salir.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lbl_salir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_salir.setText("X");
        lbl_salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_salirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_salirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_salirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitbtnLayout = new javax.swing.GroupLayout(exitbtn);
        exitbtn.setLayout(exitbtnLayout);
        exitbtnLayout.setHorizontalGroup(
            exitbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitbtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        exitbtnLayout.setVerticalGroup(
            exitbtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout barra_superiorLayout = new javax.swing.GroupLayout(barra_superior);
        barra_superior.setLayout(barra_superiorLayout);
        barra_superiorLayout.setHorizontalGroup(
            barra_superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barra_superiorLayout.createSequentialGroup()
                .addComponent(btnmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(exitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 728, Short.MAX_VALUE))
        );
        barra_superiorLayout.setVerticalGroup(
            barra_superiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(exitbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(barra_superior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 30));

        txt_user.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txt_user.setForeground(new java.awt.Color(153, 153, 153));
        txt_user.setText("Nombre de usuario");
        txt_user.setBorder(null);
        txt_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_userMousePressed(evt);
            }
        });
        jPanel1.add(txt_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 390, 20));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 400, -1));

        user_nombre.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        user_nombre.setText("NOMBRE");
        jPanel1.add(user_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        txt_nombre.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txt_nombre.setForeground(new java.awt.Color(153, 153, 153));
        txt_nombre.setText("Digite su Nombre");
        txt_nombre.setBorder(null);
        txt_nombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_nombreMousePressed(evt);
            }
        });
        txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreActionPerformed(evt);
            }
        });
        jPanel1.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 190, 20));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 180, 10));

        txt_apellido.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txt_apellido.setForeground(new java.awt.Color(153, 153, 153));
        txt_apellido.setText("Digite su Apellido");
        txt_apellido.setBorder(null);
        txt_apellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_apellidoMousePressed(evt);
            }
        });
        jPanel1.add(txt_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 190, 20));

        user_apellido.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        user_apellido.setText("APELLIDO");
        jPanel1.add(user_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, -1, -1));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 190, 10));

        correo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        correo.setText("CORREO");
        jPanel1.add(correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        txt_correo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txt_correo.setForeground(new java.awt.Color(153, 153, 153));
        txt_correo.setText("Digite un email");
        txt_correo.setBorder(null);
        txt_correo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_correoMousePressed(evt);
            }
        });
        jPanel1.add(txt_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 390, 20));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 400, -1));

        user_nombre1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        user_nombre1.setText("CONTRASEÑA");
        jPanel1.add(user_nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 180, 10));

        txt_pass.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txt_pass.setForeground(new java.awt.Color(153, 153, 153));
        txt_pass.setText("********");
        txt_pass.setBorder(null);
        txt_pass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_passMousePressed(evt);
            }
        });
        jPanel1.add(txt_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 180, 20));

        direccion.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        direccion.setText("DIRECCIÓN");
        jPanel1.add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        txt_direccion.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txt_direccion.setForeground(new java.awt.Color(153, 153, 153));
        txt_direccion.setText("Digite una Dirección");
        txt_direccion.setBorder(null);
        txt_direccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_direccionMousePressed(evt);
            }
        });
        jPanel1.add(txt_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 390, 20));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 400, -1));

        boton_registro.setBackground(new java.awt.Color(13, 25, 75));

        btn_registro.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btn_registro.setForeground(new java.awt.Color(255, 255, 255));
        btn_registro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_registro.setText("REGISTRARSE");
        btn_registro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_registro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_registroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_registroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_registroMouseExited(evt);
            }
        });

        javax.swing.GroupLayout boton_registroLayout = new javax.swing.GroupLayout(boton_registro);
        boton_registro.setLayout(boton_registroLayout);
        boton_registroLayout.setHorizontalGroup(
            boton_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_registro, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        boton_registroLayout.setVerticalGroup(
            boton_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boton_registroLayout.createSequentialGroup()
                .addComponent(btn_registro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(boton_registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, 110, 40));

        lbl_atras.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lbl_atras.setForeground(new java.awt.Color(51, 51, 255));
        lbl_atras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_atras.setText("<-- ATRAS");
        lbl_atras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_atras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_atrasMouseClicked(evt);
            }
        });
        jPanel1.add(lbl_atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, -1, -1));

        aceptoterminos.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        aceptoterminos.setText("Acepto todos los términos y condiciones ");
        aceptoterminos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptoterminosActionPerformed(evt);
            }
        });
        jPanel1.add(aceptoterminos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, -1));

        cambiar_pass.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        cambiar_pass.setText("Mostrar contraseña");
        cambiar_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiar_passActionPerformed(evt);
            }
        });
        jPanel1.add(cambiar_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_minMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_minMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_lbl_minMouseClicked

    private void lbl_minMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_minMouseEntered
        btnmin.setBackground(Color.red);
        lbl_min.setForeground(Color.white);
    }//GEN-LAST:event_lbl_minMouseEntered

    private void lbl_minMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_minMouseExited
        btnmin.setBackground(Color.white);
        lbl_min.setForeground(Color.black);
    }//GEN-LAST:event_lbl_minMouseExited

    private void lbl_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_salirMouseClicked
        Object[] opciones = {"Sí", "No"};

        int respuesta = JOptionPane.showOptionDialog(
            this,
            "¿Estás seguro de cerrar la aplicación?",
            "Confirmar cierre",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE,
            null,
            opciones,
            opciones[0]); // Puedes cambiar este índice para establecer el botón predeterminado

        if (respuesta == JOptionPane.YES_OPTION) {
            // Si el usuario elige "Sí", cierra la aplicación
            System.exit(0);
        } else {
            // Si el usuario elige "No" o cierra el cuadro de diálogo, no hace nada
        }
    }//GEN-LAST:event_lbl_salirMouseClicked

    private void lbl_salirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_salirMouseEntered
        exitbtn.setBackground(Color.red);
        lbl_salir.setForeground(Color.white);
    }//GEN-LAST:event_lbl_salirMouseEntered

    private void lbl_salirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_salirMouseExited
        exitbtn.setBackground(Color.white);
        lbl_salir.setForeground(Color.black);
    }//GEN-LAST:event_lbl_salirMouseExited

    private void barra_superiorMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barra_superiorMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_barra_superiorMouseDragged

    private void barra_superiorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barra_superiorMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_barra_superiorMousePressed

    private void txt_userMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_userMousePressed
        if (txt_user.getText().equals("Nombre de usuario")){
            txt_user.setText("");
            txt_user.setForeground(Color.black);
        }
        if (txt_nombre.getText().isEmpty()){
            txt_nombre.setText("Digite su Nombre");
            txt_nombre.setForeground(Color.gray);
        }
        if (String.valueOf(txt_pass.getPassword()).isEmpty()){
            txt_pass.setText("********");
            txt_pass.setForeground(Color.gray);
        }
        if (txt_apellido.getText().isEmpty()){
            txt_apellido.setText("Digite su Apellido");
            txt_apellido.setForeground(Color.gray);
        }
        if (txt_correo.getText().isEmpty()){
            txt_correo.setText("Digite un email");
            txt_correo.setForeground(Color.gray);
        }
        if (txt_direccion.getText().isEmpty()){
            txt_direccion.setText("Digite una Dirección");
            txt_direccion.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txt_userMousePressed

    private void txt_nombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_nombreMousePressed
        if (txt_nombre.getText().equals("Digite su Nombre")){
            txt_nombre.setText("");
            txt_nombre.setForeground(Color.black);
        }
        if (txt_user.getText().isEmpty()){
            txt_user.setText("Nombre de usuario");
            txt_user.setForeground(Color.gray);
        }
        if (String.valueOf(txt_pass.getPassword()).isEmpty()){
            txt_pass.setText("********");
            txt_pass.setForeground(Color.gray);
        }
        if (txt_apellido.getText().isEmpty()){
            txt_apellido.setText("Digite su Apellido");
            txt_apellido.setForeground(Color.gray);
        }
        if (txt_correo.getText().isEmpty()){
            txt_correo.setText("Digite un email");
            txt_correo.setForeground(Color.gray);
        }
        if (txt_direccion.getText().isEmpty()){
            txt_direccion.setText("Digite una Dirección");
            txt_direccion.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txt_nombreMousePressed

    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreActionPerformed

    private void txt_apellidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_apellidoMousePressed
        if (txt_apellido.getText().equals("Digite su Apellido")){
            txt_apellido.setText("");
            txt_apellido.setForeground(Color.black);
        }
        if (txt_user.getText().isEmpty()){
            txt_user.setText("Nombre de usuario");
            txt_user.setForeground(Color.gray);
        }
        if (String.valueOf(txt_pass.getPassword()).isEmpty()){
            txt_pass.setText("********");
            txt_pass.setForeground(Color.gray);
        }
        if (txt_nombre.getText().isEmpty()){
            txt_nombre.setText("Digite su Nombre");
            txt_nombre.setForeground(Color.gray);
        }
        if (txt_correo.getText().isEmpty()){
            txt_correo.setText("Digite un email");
            txt_correo.setForeground(Color.gray);
        }
        if (txt_direccion.getText().isEmpty()){
            txt_direccion.setText("Digite una Dirección");
            txt_direccion.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txt_apellidoMousePressed

    private void txt_correoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_correoMousePressed
        if (txt_correo.getText().equals("Digite un email")){
            txt_correo.setText("");
            txt_correo.setForeground(Color.black);
        }
        if (txt_user.getText().isEmpty()){
            txt_user.setText("Nombre de usuario");
            txt_user.setForeground(Color.gray);
        }
        if (String.valueOf(txt_pass.getPassword()).isEmpty()){
            txt_pass.setText("********");
            txt_pass.setForeground(Color.gray);
        }
        if (txt_nombre.getText().isEmpty()){
            txt_nombre.setText("Digite su Nombre");
            txt_nombre.setForeground(Color.gray);
        }
        if (txt_apellido.getText().isEmpty()){
            txt_apellido.setText("Digite su Apellido");
            txt_apellido.setForeground(Color.gray);
        }
        if (txt_direccion.getText().isEmpty()){
            txt_direccion.setText("Digite una Dirección");
            txt_direccion.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txt_correoMousePressed

    private void txt_passMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_passMousePressed
        if (String.valueOf(txt_pass.getPassword()).equals("********")){
            txt_pass.setText("");
            txt_pass.setForeground(Color.black);
        }
        if (txt_user.getText().isEmpty()){
            txt_user.setText("Nombre de usuario");
            txt_user.setForeground(Color.gray);
        }
        if (txt_nombre.getText().isEmpty()){
            txt_nombre.setText("Digite su Nombre");
            txt_nombre.setForeground(Color.gray);
        }
        if (txt_apellido.getText().isEmpty()){
            txt_apellido.setText("Digite su Apellido");
            txt_apellido.setForeground(Color.gray);
        }
        if (txt_correo.getText().isEmpty()){
            txt_correo.setText("Digite un email");
            txt_correo.setForeground(Color.gray);
        }
        if (txt_direccion.getText().isEmpty()){
            txt_direccion.setText("Digite una Dirección");
            txt_direccion.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txt_passMousePressed

    private void txt_direccionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_direccionMousePressed
        if (txt_direccion.getText().equals("Digite una Dirección")){
            txt_direccion.setText("");
            txt_direccion.setForeground(Color.black);
        }
        if (txt_user.getText().isEmpty()){
            txt_user.setText("Nombre de usuario");
            txt_user.setForeground(Color.gray);
        }
        if (String.valueOf(txt_pass.getPassword()).isEmpty()){
            txt_pass.setText("********");
            txt_pass.setForeground(Color.gray);
        }
        if (txt_nombre.getText().isEmpty()){
            txt_nombre.setText("Digite su Nombre");
            txt_nombre.setForeground(Color.gray);
        }
        if (txt_apellido.getText().isEmpty()){
            txt_apellido.setText("Digite su Apellido");
            txt_apellido.setForeground(Color.gray);
        }
        if (txt_correo.getText().isEmpty()){
            txt_correo.setText("Digite un email");
            txt_correo.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txt_direccionMousePressed

    private void btn_registroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registroMouseClicked

        conexionDB conexion = new conexionDB();
        conn = conexion.establecerConexion();

        try {
            String username = txt_user.getText();
            String name = txt_nombre.getText();
            String apellido = txt_apellido.getText();
            String email = txt_correo.getText();
            String direc = txt_direccion.getText();
            String password = new String(txt_pass.getPassword());

            // Validar campos vacíos o con texto por defecto
            if (username.isEmpty() || username.equals("Nombre de usuario") ||
                name.isEmpty() || name.equals("Digite su Nombre") ||
                apellido.isEmpty() || apellido.equals("Digite su Apellido") ||
                password.isEmpty() || password.equals("********")) {
                // Mostrar mensaje de llenar todos los campos
                JOptionPane.showMessageDialog(null, "Por favor, llene todos los campos.", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (email.isEmpty() || email.equals("Digite un email") || !isValidEmail(email)) {
                // Mostrar mensaje de correo electrónico inválido
                JOptionPane.showMessageDialog(null, "Por favor, ingrese un correo electrónico válido.", "Error", JOptionPane.ERROR_MESSAGE);
            }  else {
                // Campos llenos, imprimir información (puedes comentar esto en producción)
                //                System.out.println("Username: " + username);
                //                System.out.println("Nombre: " + name);
                //                System.out.println("Apellido: " + apellido);
                //                System.out.println("Correo: " + email);
                //                System.out.println("Dirección: " + direc);
                //                System.out.println("Contraseña: " + password);
                camposllenos = true;
            }

            // Verificar aceptación de términos y condiciones
            if (aceptoTerminos) {
                aceptoTerminos_2 = true;
            } else {
                // Muestra un mensaje de error al usuario
                JOptionPane.showMessageDialog(this, "Acepte los términos y condiciones");
            }

            // Si se aceptan términos, campos llenos y el usuario es nuevo, proceder con el registro
            if (aceptoTerminos_2 && camposllenos) {
                // La función consultaUsuario debería devolver un TipoConflicto indicando el tipo de conflicto
                TipoConflicto tipoConflicto = consultaUsuario(username, password, email);

                switch (tipoConflicto) {
                    case NINGUNO:
                    // Ni el usuario ni el correo existen, puedes proceder con tu lógica
                    System.out.println("Usuario y correo no registrados. Puedes continuar con tu lógica.");

                    // Registrar el nuevo cliente en la base de datos
                    String descrip = "Cliente";
                    insertarcliente(username, name, apellido, email, direc, password, descrip);

                    JOptionPane.showMessageDialog(this, "Registro exitoso. A continuación, debe iniciar sesión.");

                    // Iniciar sesión y redirigir al usuario a la pantalla de login
                    login a = new login();
                    a.setVisible(true);
                    dispose();
                    break;
                    case USUARIO_EXISTENTE:
                    // Usuario ya existe, muestra un mensaje
                    JOptionPane.showMessageDialog(this, "El usuario ya está registrado.");
                    break;
                    case CORREO_EXISTENTE:
                    // Correo ya existe, muestra un mensaje
                    JOptionPane.showMessageDialog(this, "El correo ya está registrado.");
                    break;
                    case AMBOS_EXISTENTES:
                    // Ambos usuario y correo existen, maneja según tus necesidades
                    // Puedes agregar aquí la lógica específica para el caso de ambos existentes
                    JOptionPane.showMessageDialog(this, "El usuario y el correo ya están registrados.");
                    break;
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
            // Manejar la excepción de manera apropiada
            JOptionPane.showMessageDialog(this, "Error durante el registro.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btn_registroMouseClicked

    private void btn_registroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registroMouseEntered
        boton_registro.setBackground(new Color(69,81,107));
    }//GEN-LAST:event_btn_registroMouseEntered

    private void btn_registroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registroMouseExited
        boton_registro.setBackground(new Color(13,25,75));
    }//GEN-LAST:event_btn_registroMouseExited

    private void lbl_atrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_atrasMouseClicked
        // Cierra la ventana actual
        this.dispose();

        // Abre una nueva ventana de Registro
        login acceso = new login();
        acceso.setVisible(true);
    }//GEN-LAST:event_lbl_atrasMouseClicked

    private void aceptoterminosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptoterminosActionPerformed
        aceptoTerminos = aceptoterminos.isSelected();

        // Puedes realizar acciones adicionales según el estado de aceptoTerminos
        if (aceptoTerminos) {
            // Acciones cuando el JCheckBox está seleccionado
            System.out.println("Acepto los terminos y condiciones.");
        } else {
            // Acciones cuando el JCheckBox no está seleccionado
            System.out.println("No acepto los terminos y condiciones.");
        }
    }//GEN-LAST:event_aceptoterminosActionPerformed

    private void cambiar_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiar_passActionPerformed
        if (cambiar_pass.isSelected()) {
            txt_pass.setEchoChar((char) 0); // Mostrar la contraseña
        } else {
            txt_pass.setEchoChar('*'); // Ocultar la contraseña
        }
    }//GEN-LAST:event_cambiar_passActionPerformed
    public void insertarcliente(String usuario, String nombre, String lastname, String correo, String address, String pwd, String detalles){
    
            int_tipo_usuariosIMP int_tipo_usariosDao;       

            int_usuarioDaoImp intUsuariosDAO;

            try {

                int_tipo_usariosDao  = new int_tipo_usuariosIMP(conn);
                intUsuariosDAO  = new int_usuarioDaoImp(conn);

                intUsuariosDAO.insertUser(usuario, nombre, lastname, correo, pwd);

                int_usuario cliente;
                cliente = intUsuariosDAO.getUserByNameAndPass(usuario, pwd);
                user_id = cliente.getId();
                
                int_tipo_usariosDao.set_Data(user_id, detalles, address);

            } catch (Exception e) {
                 e.printStackTrace();
            }   
    }
    public enum TipoConflicto {
    NINGUNO,
    USUARIO_EXISTENTE,
    CORREO_EXISTENTE,
    AMBOS_EXISTENTES
    }

    public TipoConflicto consultaUsuario(String u, String p, String e) {
        int_usuarioDaoImp intUsuariosDAO;
        intUsuariosDAO = new int_usuarioDaoImp(conn);
        int_usuario usuario;

        // Verificar si el usuario ya existe
        usuario = intUsuariosDAO.getUserByNameAndPass(u, p);
        if (usuario != null) {
            // Usuario ya existe
            return TipoConflicto.USUARIO_EXISTENTE;
        }

        // Verificar si el correo ya existe
        usuario = intUsuariosDAO.getUserByEmailAndPass(e, p);
        if (usuario != null) {
            // Correo ya existe
            return TipoConflicto.CORREO_EXISTENTE;
        }

        // Si llegamos a este punto, ni el usuario ni el correo existen
        return TipoConflicto.NINGUNO;
    }

    // Función para validar un correo electrónico
    private boolean isValidEmail(String email) {
        // Verifica si el correo electrónico contiene el carácter "@"
        return email.contains("@");
    }
    
    
    public int getUserID() {
        return user_id;
    }
    public Connection getConn() {
        return conn;
    }   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox aceptoterminos;
    private javax.swing.JPanel barra_superior;
    private javax.swing.JPanel boton_registro;
    private javax.swing.JLabel btn_registro;
    private javax.swing.JPanel btnmin;
    private javax.swing.JCheckBox cambiar_pass;
    private javax.swing.JLabel correo;
    private javax.swing.JLabel direccion;
    private javax.swing.JPanel exitbtn;
    private javax.swing.JLabel fdbg;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lbl_atras;
    private javax.swing.JLabel lbl_min;
    private javax.swing.JLabel lbl_salir;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_correo;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JPasswordField txt_pass;
    private javax.swing.JTextField txt_user;
    private javax.swing.JLabel user;
    private javax.swing.JLabel user_apellido;
    private javax.swing.JLabel user_nombre;
    private javax.swing.JLabel user_nombre1;
    // End of variables declaration//GEN-END:variables
}
